spring:
  r2dbc:
    url: r2dbc:mysql://133.186.240.224:3306/webflux
    username: webflux
    password: webflux
    name: webflux
    pool:
      validation-query: select 'r2dbc'
      max-size: 3
      initial-size: 3
      max-idle-time: 5m
  data:
    mongodb:
      database: webflux
      username: webflux
      password: webflux
      host: 133.186.240.224
      port: 3307
  redis:
    url: redis://133.186.240.224:3308
  kafka:
    bootstrap-servers: 133.186.240.224:9092