server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: webflux
    password: webflux
    name: webflux
    pool:
      validation-query: select 'r2dbc'
      max-size: 3
      initial-size: 3
      max-idle-time: 5m
  data:
    mongodb:
      database: webflux
      username: webflux
      password: webflux
      host: localhost
      port: 3307
  redis:
    url: redis://localhost:3308
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.r2dbc.core: DEBUG
    org.springframework.r2dbc.connection: DEBUG
    org.springframework.data.mongodb.core: WARN
    org.mongodb.driver.protocol.command: DEBUG
    org.springframework.kafka: DEBUG
    reactor.kafka: DEBUG
#    org.apache.kafka.clients: DEBUG
    org.mongodb: OFF

    io.lettuce.core.protocol.CommandHandler: DEBUG

    com.nhn.webflux2021: DEBUG

    root: INFO
#    io.netty: DEBUG
#    reactor.netty: DEBUG
#    org.springframework.web: TRACE
#    org.springframework.mongodb: TRACE
    org.springframework: OFF
#    io.lettuce: DEBUG