version: '3.9'

services:
  db:
    container_name: mysql
    hostname: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=webflux
      - MYSQL_USER=webflux
      - MYSQL_PASSWORD=webflux
      - MYSQL_DATABASE=webflux
    volumes:
      - ./mysql:/var/lib/mysql

  # 최초 한번 계정생성 (dockerfile를 수정해서 하는건 너무 귀찮...)
  # docker exec -it mongo /bin/sh
  # mongo -u nhn -p nhn
  # use webflux
  # db.createUser({user: "webflux", pwd: "webflux", roles: ["readWrite"]})
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "3307:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nhn
      - MONGO_INITDB_ROOT_PASSWORD=nhn
      - MONGO_INITDB_DATABASE=webflux
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    ports:
      - "3308:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  # /bin/kafka-topics --create --topic NHN --bootstrap-server localhost:9092
  # /bin/kafka-topics --describe --topic NHN --bootstrap-server localhost:9092
  # /bin/kafka-console-producer --topic NHN --bootstrap-server localhost:9092
  # /bin/kafka-console-consumer --topic NHN --bootstrap-server localhost:9092
  # /bin/kafka-topics --delete --topic NHN --bootstrap-server localhost:9092
  kafka:
    image: confluentinc/cp-server:6.1.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_PLAIN_TEXT}:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

networks:
  default:
    name: webflux